---
title: BCCO NYC
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  blog:
    title: blog
    output: true
email: info@bcconyc.com
description: "Custom T shirts NYC, screen printing, embroidery, DTG printing, Vinyl
  printing. \nDTG PRINTING, Screen printing, SAME DAY SERVICE.\n1697 Broadway #302,
  New York, NY 10019"
baseurl: 
url: 
theme: minima
plugins:
- jekyll-feed
