---
title: BCCO NYC
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@bcconyc.com
description: "Custom T shirts NYC, screen printing, embroidery, DTG printing, Vinyl
  printing \n\nDTG PRINTING, Screen printing, SAME DAY SERVICE"
baseurl: 
url: 
theme: minima
plugins:
- jekyll-feed
